system:

commands:
  gnome: gnome-terminal -e "ssh -i ~/.ssh/meklis  %username%@%host%"
  gnome-password: gnome-terminal -e "ssh -i ~/.ssh/meklis  %username%@%host%"

groups:
  - name: General
    defaults:
      command: gnome
      username: meklis
      password: abracadabra
      ssh_key: ~/.ssh/id_rsa
    servers_source: ~/server.json
    servers:
    - {name: office.pc, host: 10.0.10.10, username: username, password: passwprd,  }
    - {name: office2.pc, host: 10.0.10.1, username: username, password: passwprd, ssh_key: ~/.ssh/id_rsa }

